"""
============================================================================
 KAStarAgg — full event-stream pins on the canonical OMSPP
 problem (`Factory.grid_4x4_obstacle_omspp`: start (0,0),
 goals (0,3) / (3,0) / (3,3); per-goal optimal costs 7 / 3 / 6;
 Manhattan h to each goal). Aggregator: MIN (the canonical
 aggregator; is_opt requires agg ∈ {MIN, MAX}).

 One test per param-config (8 total = 2³ combinations of
 `is_lazy` × `is_opt` × `store_vector`). Each asserts the
 complete normalized event list (every field of every event,
 `duration` stripped). Distinguishing event signatures per
 config (per `KAStarAgg/CLAUDE.md`):

   - `is_lazy=False`  → `update_frontier` markers fire on
     eager refresh boundaries.
   - `is_lazy=True`   → `pop_stale` events fire on lazy
     stale-pop re-checks.
   - `is_opt=True`    → `responsible_set` and `refresh_skip`
     events fire when the responsible-goal optimisation
     short-circuits.
   - `store_vector=True` → `h_calc` count drops to zero after
     each state's first vector cache; subsequent
     `phi_calc`s consume the cached vector.
============================================================================
"""

from f_hs.algo.i_1_omspp.i_1_kastar_agg import KAStarAgg
from f_hs.algo.u_event_normalize import normalize
from f_hs.problem.i_1_grid import ProblemGrid




# === eager_noopt_nosv (106 events) ===
def test_recording_canonical_omspp_min_eager_noopt_nosv() -> None:
    """
    ========================================================================
     Pin the FULL event stream for KAStarAgg-MIN with
     is_lazy=False, is_opt=False, store_vector=False.
     106 events.
    ========================================================================
    """
    p = ProblemGrid.Factory.grid_4x4_obstacle_omspp()
    algo = KAStarAgg(problem=p,
                     h=lambda s, g: float(s.distance(g)),
                     agg='MIN',
                     is_lazy=False,
                     is_opt=False,
                     store_vector=False,
                     is_recording=True)
    algo.run()
    actual = [normalize(e) for e in algo.recorder.events]
    expected = [
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 6, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (0, 0), 'g': 0, 'parent': None, 'h': 3, 'f': 3},
        {'type': 'pop', 'state': (0, 0), 'g': 0, 'h': 3, 'f': 3},
        {'type': 'h_calc', 'state': (0, 1), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 4, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (0, 1), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 0), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (1, 0), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'pop', 'state': (0, 1), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (1, 1), 'g': 2, 'parent': (0, 1), 'h': 3, 'f': 5},
        {'type': 'pop', 'state': (1, 0), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (2, 0), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 1, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (2, 0), 'g': 2, 'parent': (1, 0), 'h': 1, 'f': 3},
        {'type': 'pop', 'state': (2, 0), 'g': 2, 'h': 1, 'f': 3},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 1), 'g': 3, 'parent': (2, 0), 'h': 2, 'f': 5},
        {'type': 'h_calc', 'state': (3, 0), 'value': 6, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 0, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 0), 'g': 3, 'parent': (2, 0), 'h': 0, 'f': 3},
        {'type': 'pop', 'state': (3, 0), 'g': 3, 'h': 0, 'f': 3},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (3, 1), 'g': 4, 'parent': (3, 0), 'h': 2, 'f': 6},
        {'type': 'on_goal', 'state': (3, 0), 'g': 3, 'reason': 'expanded', 'goal_index': 1},
        {'type': 'update_frontier', 'num_nodes': 3, 'next_goal_index': 0},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 2, 'h_new': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (1, 1), 'h_old': 3, 'h_new': 3},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (3, 1), 'h_old': 2, 'h_new': 2},
        {'type': 'pop', 'state': (1, 1), 'g': 2, 'h': 3, 'f': 5},
        {'type': 'pop', 'state': (3, 1), 'g': 4, 'h': 2, 'f': 6},
        {'type': 'h_calc', 'state': (3, 2), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 2), 'value': 1, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (3, 2), 'g': 5, 'parent': (3, 1), 'h': 1, 'f': 6},
        {'type': 'pop', 'state': (3, 2), 'g': 5, 'h': 1, 'f': 6},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 2), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 2), 'g': 6, 'parent': (3, 2), 'h': 2, 'f': 8},
        {'type': 'h_calc', 'state': (3, 3), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 3), 'value': 0, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 3), 'g': 6, 'parent': (3, 2), 'h': 0, 'f': 6},
        {'type': 'pop', 'state': (3, 3), 'g': 6, 'h': 0, 'f': 6},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 3), 'g': 7, 'parent': (3, 3), 'h': 2, 'f': 9},
        {'type': 'on_goal', 'state': (3, 3), 'g': 6, 'reason': 'expanded', 'goal_index': 2},
        {'type': 'update_frontier', 'num_nodes': 3, 'next_goal_index': 0},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 3, 'h_new': 4},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 2), 'h_old': 2, 'h_new': 3},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 3), 'h_old': 2, 'h_new': 2},
        {'type': 'pop', 'state': (2, 1), 'g': 3, 'h': 4, 'f': 7},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 2), 'g': 4, 'parent': (2, 1), 'h': 3, 'f': 7},
        {'type': 'pop', 'state': (2, 2), 'g': 4, 'h': 3, 'f': 7},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 3), 'g': 5, 'parent': (2, 2), 'h': 2, 'f': 7},
        {'type': 'pop', 'state': (2, 3), 'g': 5, 'h': 2, 'f': 7},
        {'type': 'h_calc', 'state': (1, 3), 'value': 1, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (1, 3), 'g': 6, 'parent': (2, 3), 'h': 1, 'f': 7},
        {'type': 'pop', 'state': (1, 3), 'g': 6, 'h': 1, 'f': 7},
        {'type': 'h_calc', 'state': (0, 3), 'value': 0, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (0, 3), 'g': 7, 'parent': (1, 3), 'h': 0, 'f': 7},
        {'type': 'pop', 'state': (0, 3), 'g': 7, 'h': 0, 'f': 7},
        {'type': 'on_goal', 'state': (0, 3), 'g': 7, 'reason': 'expanded', 'goal_index': 0},
    ]
    assert actual == expected


# === eager_noopt_sv (95 events) ===
def test_recording_canonical_omspp_min_eager_noopt_sv() -> None:
    """
    ========================================================================
     Pin the FULL event stream for KAStarAgg-MIN with
     is_lazy=False, is_opt=False, store_vector=True.
     95 events.
    ========================================================================
    """
    p = ProblemGrid.Factory.grid_4x4_obstacle_omspp()
    algo = KAStarAgg(problem=p,
                     h=lambda s, g: float(s.distance(g)),
                     agg='MIN',
                     is_lazy=False,
                     is_opt=False,
                     store_vector=True,
                     is_recording=True)
    algo.run()
    actual = [normalize(e) for e in algo.recorder.events]
    expected = [
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 6, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (0, 0), 'g': 0, 'parent': None, 'h': 3, 'f': 3},
        {'type': 'pop', 'state': (0, 0), 'g': 0, 'h': 3, 'f': 3},
        {'type': 'h_calc', 'state': (0, 1), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 4, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (0, 1), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 0), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (1, 0), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'pop', 'state': (0, 1), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (1, 1), 'g': 2, 'parent': (0, 1), 'h': 3, 'f': 5},
        {'type': 'pop', 'state': (1, 0), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (2, 0), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 1, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (2, 0), 'g': 2, 'parent': (1, 0), 'h': 1, 'f': 3},
        {'type': 'pop', 'state': (2, 0), 'g': 2, 'h': 1, 'f': 3},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 1), 'g': 3, 'parent': (2, 0), 'h': 2, 'f': 5},
        {'type': 'h_calc', 'state': (3, 0), 'value': 6, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 0, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 0), 'g': 3, 'parent': (2, 0), 'h': 0, 'f': 3},
        {'type': 'pop', 'state': (3, 0), 'g': 3, 'h': 0, 'f': 3},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (3, 1), 'g': 4, 'parent': (3, 0), 'h': 2, 'f': 6},
        {'type': 'on_goal', 'state': (3, 0), 'g': 3, 'reason': 'expanded', 'goal_index': 1},
        {'type': 'update_frontier', 'num_nodes': 3, 'next_goal_index': 0},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 2, 'h_new': 3},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (1, 1), 'h_old': 3, 'h_new': 3},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (3, 1), 'h_old': 2, 'h_new': 2},
        {'type': 'pop', 'state': (1, 1), 'g': 2, 'h': 3, 'f': 5},
        {'type': 'pop', 'state': (3, 1), 'g': 4, 'h': 2, 'f': 6},
        {'type': 'h_calc', 'state': (3, 2), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 2), 'value': 1, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (3, 2), 'g': 5, 'parent': (3, 1), 'h': 1, 'f': 6},
        {'type': 'pop', 'state': (3, 2), 'g': 5, 'h': 1, 'f': 6},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 2), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 2), 'g': 6, 'parent': (3, 2), 'h': 2, 'f': 8},
        {'type': 'h_calc', 'state': (3, 3), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 3), 'value': 0, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 3), 'g': 6, 'parent': (3, 2), 'h': 0, 'f': 6},
        {'type': 'pop', 'state': (3, 3), 'g': 6, 'h': 0, 'f': 6},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 3), 'g': 7, 'parent': (3, 3), 'h': 2, 'f': 9},
        {'type': 'on_goal', 'state': (3, 3), 'g': 6, 'reason': 'expanded', 'goal_index': 2},
        {'type': 'update_frontier', 'num_nodes': 3, 'next_goal_index': 0},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 3, 'h_new': 4},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 2), 'h_old': 2, 'h_new': 3},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 3), 'h_old': 2, 'h_new': 2},
        {'type': 'pop', 'state': (2, 1), 'g': 3, 'h': 4, 'f': 7},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 2), 'g': 4, 'parent': (2, 1), 'h': 3, 'f': 7},
        {'type': 'pop', 'state': (2, 2), 'g': 4, 'h': 3, 'f': 7},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 3), 'g': 5, 'parent': (2, 2), 'h': 2, 'f': 7},
        {'type': 'pop', 'state': (2, 3), 'g': 5, 'h': 2, 'f': 7},
        {'type': 'h_calc', 'state': (1, 3), 'value': 1, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (1, 3), 'g': 6, 'parent': (2, 3), 'h': 1, 'f': 7},
        {'type': 'pop', 'state': (1, 3), 'g': 6, 'h': 1, 'f': 7},
        {'type': 'h_calc', 'state': (0, 3), 'value': 0, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (0, 3), 'g': 7, 'parent': (1, 3), 'h': 0, 'f': 7},
        {'type': 'pop', 'state': (0, 3), 'g': 7, 'h': 0, 'f': 7},
        {'type': 'on_goal', 'state': (0, 3), 'g': 7, 'reason': 'expanded', 'goal_index': 0},
    ]
    assert actual == expected


# === eager_opt_nosv (117 events) ===
def test_recording_canonical_omspp_min_eager_opt_nosv() -> None:
    """
    ========================================================================
     Pin the FULL event stream for KAStarAgg-MIN with
     is_lazy=False, is_opt=True, store_vector=False.
     117 events.
    ========================================================================
    """
    p = ProblemGrid.Factory.grid_4x4_obstacle_omspp()
    algo = KAStarAgg(problem=p,
                     h=lambda s, g: float(s.distance(g)),
                     agg='MIN',
                     is_lazy=False,
                     is_opt=True,
                     store_vector=False,
                     is_recording=True)
    algo.run()
    actual = [normalize(e) for e in algo.recorder.events]
    expected = [
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 6, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (0, 0), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (0, 0), 'g': 0, 'parent': None, 'h': 3, 'f': 3},
        {'type': 'pop', 'state': (0, 0), 'g': 0, 'h': 3, 'f': 3},
        {'type': 'h_calc', 'state': (0, 1), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 4, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (0, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (0, 1), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 0), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (1, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (1, 0), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'pop', 'state': (0, 1), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (1, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (1, 1), 'g': 2, 'parent': (0, 1), 'h': 3, 'f': 5},
        {'type': 'pop', 'state': (1, 0), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (2, 0), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 1, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (2, 0), 'g': 2, 'parent': (1, 0), 'h': 1, 'f': 3},
        {'type': 'pop', 'state': (2, 0), 'g': 2, 'h': 1, 'f': 3},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 1), 'g': 3, 'parent': (2, 0), 'h': 2, 'f': 5},
        {'type': 'h_calc', 'state': (3, 0), 'value': 6, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 0, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 0), 'g': 3, 'parent': (2, 0), 'h': 0, 'f': 3},
        {'type': 'pop', 'state': (3, 0), 'g': 3, 'h': 0, 'f': 3},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 1), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (3, 1), 'g': 4, 'parent': (3, 0), 'h': 2, 'f': 6},
        {'type': 'on_goal', 'state': (3, 0), 'g': 3, 'reason': 'expanded', 'goal_index': 1},
        {'type': 'update_frontier', 'num_nodes': 3, 'next_goal_index': 0},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 2, 'h_new': 3},
        {'type': 'refresh_skip', 'state': (1, 1), 'reason': 'eager_responsible_unchanged'},
        {'type': 'refresh_skip', 'state': (3, 1), 'reason': 'eager_responsible_unchanged'},
        {'type': 'pop', 'state': (1, 1), 'g': 2, 'h': 3, 'f': 5},
        {'type': 'pop', 'state': (3, 1), 'g': 4, 'h': 2, 'f': 6},
        {'type': 'h_calc', 'state': (3, 2), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 2), 'value': 1, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 2), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (3, 2), 'g': 5, 'parent': (3, 1), 'h': 1, 'f': 6},
        {'type': 'pop', 'state': (3, 2), 'g': 5, 'h': 1, 'f': 6},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 2), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 2), 'g': 6, 'parent': (3, 2), 'h': 2, 'f': 8},
        {'type': 'h_calc', 'state': (3, 3), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 3), 'value': 0, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 3), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 3), 'g': 6, 'parent': (3, 2), 'h': 0, 'f': 6},
        {'type': 'pop', 'state': (3, 3), 'g': 6, 'h': 0, 'f': 6},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 3), 'g': 7, 'parent': (3, 3), 'h': 2, 'f': 9},
        {'type': 'on_goal', 'state': (3, 3), 'g': 6, 'reason': 'expanded', 'goal_index': 2},
        {'type': 'update_frontier', 'num_nodes': 3, 'next_goal_index': 0},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 3, 'h_new': 4},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 2), 'h_old': 2, 'h_new': 3},
        {'type': 'refresh_skip', 'state': (2, 3), 'reason': 'eager_responsible_unchanged'},
        {'type': 'pop', 'state': (2, 1), 'g': 3, 'h': 4, 'f': 7},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 2), 'g': 4, 'parent': (2, 1), 'h': 3, 'f': 7},
        {'type': 'pop', 'state': (2, 2), 'g': 4, 'h': 3, 'f': 7},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 3), 'g': 5, 'parent': (2, 2), 'h': 2, 'f': 7},
        {'type': 'pop', 'state': (2, 3), 'g': 5, 'h': 2, 'f': 7},
        {'type': 'h_calc', 'state': (1, 3), 'value': 1, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (1, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (1, 3), 'g': 6, 'parent': (2, 3), 'h': 1, 'f': 7},
        {'type': 'pop', 'state': (1, 3), 'g': 6, 'h': 1, 'f': 7},
        {'type': 'h_calc', 'state': (0, 3), 'value': 0, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (0, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (0, 3), 'g': 7, 'parent': (1, 3), 'h': 0, 'f': 7},
        {'type': 'pop', 'state': (0, 3), 'g': 7, 'h': 0, 'f': 7},
        {'type': 'on_goal', 'state': (0, 3), 'g': 7, 'reason': 'expanded', 'goal_index': 0},
    ]
    assert actual == expected


# === eager_opt_sv (111 events) ===
def test_recording_canonical_omspp_min_eager_opt_sv() -> None:
    """
    ========================================================================
     Pin the FULL event stream for KAStarAgg-MIN with
     is_lazy=False, is_opt=True, store_vector=True.
     111 events.
    ========================================================================
    """
    p = ProblemGrid.Factory.grid_4x4_obstacle_omspp()
    algo = KAStarAgg(problem=p,
                     h=lambda s, g: float(s.distance(g)),
                     agg='MIN',
                     is_lazy=False,
                     is_opt=True,
                     store_vector=True,
                     is_recording=True)
    algo.run()
    actual = [normalize(e) for e in algo.recorder.events]
    expected = [
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 6, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (0, 0), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (0, 0), 'g': 0, 'parent': None, 'h': 3, 'f': 3},
        {'type': 'pop', 'state': (0, 0), 'g': 0, 'h': 3, 'f': 3},
        {'type': 'h_calc', 'state': (0, 1), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 4, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (0, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (0, 1), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 0), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (1, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (1, 0), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'pop', 'state': (0, 1), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (1, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (1, 1), 'g': 2, 'parent': (0, 1), 'h': 3, 'f': 5},
        {'type': 'pop', 'state': (1, 0), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (2, 0), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 1, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (2, 0), 'g': 2, 'parent': (1, 0), 'h': 1, 'f': 3},
        {'type': 'pop', 'state': (2, 0), 'g': 2, 'h': 1, 'f': 3},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 1), 'g': 3, 'parent': (2, 0), 'h': 2, 'f': 5},
        {'type': 'h_calc', 'state': (3, 0), 'value': 6, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 0, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 0), 'g': 3, 'parent': (2, 0), 'h': 0, 'f': 3},
        {'type': 'pop', 'state': (3, 0), 'g': 3, 'h': 0, 'f': 3},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 1), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (3, 1), 'g': 4, 'parent': (3, 0), 'h': 2, 'f': 6},
        {'type': 'on_goal', 'state': (3, 0), 'g': 3, 'reason': 'expanded', 'goal_index': 1},
        {'type': 'update_frontier', 'num_nodes': 3, 'next_goal_index': 0},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 2, 'h_new': 3},
        {'type': 'refresh_skip', 'state': (1, 1), 'reason': 'eager_responsible_unchanged'},
        {'type': 'refresh_skip', 'state': (3, 1), 'reason': 'eager_responsible_unchanged'},
        {'type': 'pop', 'state': (1, 1), 'g': 2, 'h': 3, 'f': 5},
        {'type': 'pop', 'state': (3, 1), 'g': 4, 'h': 2, 'f': 6},
        {'type': 'h_calc', 'state': (3, 2), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 2), 'value': 1, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 2), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (3, 2), 'g': 5, 'parent': (3, 1), 'h': 1, 'f': 6},
        {'type': 'pop', 'state': (3, 2), 'g': 5, 'h': 1, 'f': 6},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 2), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 2), 'g': 6, 'parent': (3, 2), 'h': 2, 'f': 8},
        {'type': 'h_calc', 'state': (3, 3), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 3), 'value': 0, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 3), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 3), 'g': 6, 'parent': (3, 2), 'h': 0, 'f': 6},
        {'type': 'pop', 'state': (3, 3), 'g': 6, 'h': 0, 'f': 6},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 3), 'g': 7, 'parent': (3, 3), 'h': 2, 'f': 9},
        {'type': 'on_goal', 'state': (3, 3), 'g': 6, 'reason': 'expanded', 'goal_index': 2},
        {'type': 'update_frontier', 'num_nodes': 3, 'next_goal_index': 0},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 3, 'h_new': 4},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'update'},
        {'type': 'update_heuristic', 'state': (2, 2), 'h_old': 2, 'h_new': 3},
        {'type': 'refresh_skip', 'state': (2, 3), 'reason': 'eager_responsible_unchanged'},
        {'type': 'pop', 'state': (2, 1), 'g': 3, 'h': 4, 'f': 7},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 2), 'g': 4, 'parent': (2, 1), 'h': 3, 'f': 7},
        {'type': 'pop', 'state': (2, 2), 'g': 4, 'h': 3, 'f': 7},
        {'type': 'responsible_set', 'state': (2, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 3), 'g': 5, 'parent': (2, 2), 'h': 2, 'f': 7},
        {'type': 'pop', 'state': (2, 3), 'g': 5, 'h': 2, 'f': 7},
        {'type': 'h_calc', 'state': (1, 3), 'value': 1, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (1, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (1, 3), 'g': 6, 'parent': (2, 3), 'h': 1, 'f': 7},
        {'type': 'pop', 'state': (1, 3), 'g': 6, 'h': 1, 'f': 7},
        {'type': 'h_calc', 'state': (0, 3), 'value': 0, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (0, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (0, 3), 'g': 7, 'parent': (1, 3), 'h': 0, 'f': 7},
        {'type': 'pop', 'state': (0, 3), 'g': 7, 'h': 0, 'f': 7},
        {'type': 'on_goal', 'state': (0, 3), 'g': 7, 'reason': 'expanded', 'goal_index': 0},
    ]
    assert actual == expected


# === lazy_noopt_nosv (134 events) ===
def test_recording_canonical_omspp_min_lazy_noopt_nosv() -> None:
    """
    ========================================================================
     Pin the FULL event stream for KAStarAgg-MIN with
     is_lazy=True, is_opt=False, store_vector=False.
     134 events.
    ========================================================================
    """
    p = ProblemGrid.Factory.grid_4x4_obstacle_omspp()
    algo = KAStarAgg(problem=p,
                     h=lambda s, g: float(s.distance(g)),
                     agg='MIN',
                     is_lazy=True,
                     is_opt=False,
                     store_vector=False,
                     is_recording=True)
    algo.run()
    actual = [normalize(e) for e in algo.recorder.events]
    expected = [
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 6, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (0, 0), 'g': 0, 'parent': None, 'h': 3, 'f': 3},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'update', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 6, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'update'},
        {'type': 'pop', 'state': (0, 0), 'g': 0, 'h': 3, 'f': 3},
        {'type': 'h_calc', 'state': (0, 1), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 4, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (0, 1), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 0), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (1, 0), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (0, 1), 'value': 2, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 4, 'phase': 'update', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 5, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'update'},
        {'type': 'pop', 'state': (0, 1), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (1, 1), 'g': 2, 'parent': (0, 1), 'h': 3, 'f': 5},
        {'type': 'h_calc', 'state': (1, 0), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 2, 'phase': 'update', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 5, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'update'},
        {'type': 'pop', 'state': (1, 0), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (2, 0), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 1, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (2, 0), 'g': 2, 'parent': (1, 0), 'h': 1, 'f': 3},
        {'type': 'h_calc', 'state': (2, 0), 'value': 5, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 1, 'phase': 'update', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 4, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'update'},
        {'type': 'pop', 'state': (2, 0), 'g': 2, 'h': 1, 'f': 3},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 1), 'g': 3, 'parent': (2, 0), 'h': 2, 'f': 5},
        {'type': 'h_calc', 'state': (3, 0), 'value': 6, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 0, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 0), 'g': 3, 'parent': (2, 0), 'h': 0, 'f': 3},
        {'type': 'h_calc', 'state': (3, 0), 'value': 6, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 0, 'phase': 'update', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 3, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'update'},
        {'type': 'pop', 'state': (3, 0), 'g': 3, 'h': 0, 'f': 3},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (3, 1), 'g': 4, 'parent': (3, 0), 'h': 2, 'f': 6},
        {'type': 'on_goal', 'state': (3, 0), 'g': 3, 'reason': 'expanded', 'goal_index': 1},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 3, 'phase': 'update'},
        {'type': 'pop_stale', 'state': (2, 1), 'f_stored': 5, 'f_recomputed': 6},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 2, 'h_new': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'update'},
        {'type': 'pop', 'state': (1, 1), 'g': 2, 'h': 3, 'f': 5},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'update'},
        {'type': 'pop', 'state': (3, 1), 'g': 4, 'h': 2, 'f': 6},
        {'type': 'h_calc', 'state': (3, 2), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 2), 'value': 1, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (3, 2), 'g': 5, 'parent': (3, 1), 'h': 1, 'f': 6},
        {'type': 'h_calc', 'state': (3, 2), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 2), 'value': 1, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'update'},
        {'type': 'pop', 'state': (3, 2), 'g': 5, 'h': 1, 'f': 6},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 2), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 2), 'g': 6, 'parent': (3, 2), 'h': 2, 'f': 8},
        {'type': 'h_calc', 'state': (3, 3), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 3), 'value': 0, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 3), 'g': 6, 'parent': (3, 2), 'h': 0, 'f': 6},
        {'type': 'h_calc', 'state': (3, 3), 'value': 3, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 3), 'value': 0, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'update'},
        {'type': 'pop', 'state': (3, 3), 'g': 6, 'h': 0, 'f': 6},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 3), 'g': 7, 'parent': (3, 3), 'h': 2, 'f': 9},
        {'type': 'on_goal', 'state': (3, 3), 'g': 6, 'reason': 'expanded', 'goal_index': 2},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'pop_stale', 'state': (2, 1), 'f_stored': 6, 'f_recomputed': 7},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 3, 'h_new': 4},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'pop', 'state': (2, 1), 'g': 3, 'h': 4, 'f': 7},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 2), 'g': 4, 'parent': (2, 1), 'h': 3, 'f': 7},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'update'},
        {'type': 'pop', 'state': (2, 2), 'g': 4, 'h': 3, 'f': 7},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 3), 'g': 5, 'parent': (2, 2), 'h': 2, 'f': 7},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'update'},
        {'type': 'pop', 'state': (2, 3), 'g': 5, 'h': 2, 'f': 7},
        {'type': 'h_calc', 'state': (1, 3), 'value': 1, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (1, 3), 'g': 6, 'parent': (2, 3), 'h': 1, 'f': 7},
        {'type': 'h_calc', 'state': (1, 3), 'value': 1, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'update'},
        {'type': 'pop', 'state': (1, 3), 'g': 6, 'h': 1, 'f': 7},
        {'type': 'h_calc', 'state': (0, 3), 'value': 0, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (0, 3), 'g': 7, 'parent': (1, 3), 'h': 0, 'f': 7},
        {'type': 'h_calc', 'state': (0, 3), 'value': 0, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'update'},
        {'type': 'pop', 'state': (0, 3), 'g': 7, 'h': 0, 'f': 7},
        {'type': 'on_goal', 'state': (0, 3), 'g': 7, 'reason': 'expanded', 'goal_index': 0},
    ]
    assert actual == expected


# === lazy_noopt_sv (101 events) ===
def test_recording_canonical_omspp_min_lazy_noopt_sv() -> None:
    """
    ========================================================================
     Pin the FULL event stream for KAStarAgg-MIN with
     is_lazy=True, is_opt=False, store_vector=True.
     101 events.
    ========================================================================
    """
    p = ProblemGrid.Factory.grid_4x4_obstacle_omspp()
    algo = KAStarAgg(problem=p,
                     h=lambda s, g: float(s.distance(g)),
                     agg='MIN',
                     is_lazy=True,
                     is_opt=False,
                     store_vector=True,
                     is_recording=True)
    algo.run()
    actual = [normalize(e) for e in algo.recorder.events]
    expected = [
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 6, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (0, 0), 'g': 0, 'parent': None, 'h': 3, 'f': 3},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'update'},
        {'type': 'pop', 'state': (0, 0), 'g': 0, 'h': 3, 'f': 3},
        {'type': 'h_calc', 'state': (0, 1), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 4, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (0, 1), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 0), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (1, 0), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'update'},
        {'type': 'pop', 'state': (0, 1), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (1, 1), 'g': 2, 'parent': (0, 1), 'h': 3, 'f': 5},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'update'},
        {'type': 'pop', 'state': (1, 0), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (2, 0), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 1, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (2, 0), 'g': 2, 'parent': (1, 0), 'h': 1, 'f': 3},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'update'},
        {'type': 'pop', 'state': (2, 0), 'g': 2, 'h': 1, 'f': 3},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 1), 'g': 3, 'parent': (2, 0), 'h': 2, 'f': 5},
        {'type': 'h_calc', 'state': (3, 0), 'value': 6, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 0, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 0), 'g': 3, 'parent': (2, 0), 'h': 0, 'f': 3},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'update'},
        {'type': 'pop', 'state': (3, 0), 'g': 3, 'h': 0, 'f': 3},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (3, 1), 'g': 4, 'parent': (3, 0), 'h': 2, 'f': 6},
        {'type': 'on_goal', 'state': (3, 0), 'g': 3, 'reason': 'expanded', 'goal_index': 1},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 3, 'phase': 'update'},
        {'type': 'pop_stale', 'state': (2, 1), 'f_stored': 5, 'f_recomputed': 6},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 2, 'h_new': 3},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'update'},
        {'type': 'pop', 'state': (1, 1), 'g': 2, 'h': 3, 'f': 5},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'update'},
        {'type': 'pop', 'state': (3, 1), 'g': 4, 'h': 2, 'f': 6},
        {'type': 'h_calc', 'state': (3, 2), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 2), 'value': 1, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (3, 2), 'g': 5, 'parent': (3, 1), 'h': 1, 'f': 6},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'update'},
        {'type': 'pop', 'state': (3, 2), 'g': 5, 'h': 1, 'f': 6},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 2), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 2), 'g': 6, 'parent': (3, 2), 'h': 2, 'f': 8},
        {'type': 'h_calc', 'state': (3, 3), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 3), 'value': 0, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 3), 'g': 6, 'parent': (3, 2), 'h': 0, 'f': 6},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'update'},
        {'type': 'pop', 'state': (3, 3), 'g': 6, 'h': 0, 'f': 6},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 3), 'g': 7, 'parent': (3, 3), 'h': 2, 'f': 9},
        {'type': 'on_goal', 'state': (3, 3), 'g': 6, 'reason': 'expanded', 'goal_index': 2},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'pop_stale', 'state': (2, 1), 'f_stored': 6, 'f_recomputed': 7},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 3, 'h_new': 4},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'pop', 'state': (2, 1), 'g': 3, 'h': 4, 'f': 7},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 2), 'g': 4, 'parent': (2, 1), 'h': 3, 'f': 7},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'update'},
        {'type': 'pop', 'state': (2, 2), 'g': 4, 'h': 3, 'f': 7},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 3), 'g': 5, 'parent': (2, 2), 'h': 2, 'f': 7},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'update'},
        {'type': 'pop', 'state': (2, 3), 'g': 5, 'h': 2, 'f': 7},
        {'type': 'h_calc', 'state': (1, 3), 'value': 1, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (1, 3), 'g': 6, 'parent': (2, 3), 'h': 1, 'f': 7},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'update'},
        {'type': 'pop', 'state': (1, 3), 'g': 6, 'h': 1, 'f': 7},
        {'type': 'h_calc', 'state': (0, 3), 'value': 0, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (0, 3), 'g': 7, 'parent': (1, 3), 'h': 0, 'f': 7},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'update'},
        {'type': 'pop', 'state': (0, 3), 'g': 7, 'h': 0, 'f': 7},
        {'type': 'on_goal', 'state': (0, 3), 'g': 7, 'reason': 'expanded', 'goal_index': 0},
    ]
    assert actual == expected


# === lazy_opt_nosv (124 events) ===
def test_recording_canonical_omspp_min_lazy_opt_nosv() -> None:
    """
    ========================================================================
     Pin the FULL event stream for KAStarAgg-MIN with
     is_lazy=True, is_opt=True, store_vector=False.
     124 events.
    ========================================================================
    """
    p = ProblemGrid.Factory.grid_4x4_obstacle_omspp()
    algo = KAStarAgg(problem=p,
                     h=lambda s, g: float(s.distance(g)),
                     agg='MIN',
                     is_lazy=True,
                     is_opt=True,
                     store_vector=False,
                     is_recording=True)
    algo.run()
    actual = [normalize(e) for e in algo.recorder.events]
    expected = [
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 6, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (0, 0), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (0, 0), 'g': 0, 'parent': None, 'h': 3, 'f': 3},
        {'type': 'refresh_skip', 'state': (0, 0), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (0, 0), 'g': 0, 'h': 3, 'f': 3},
        {'type': 'h_calc', 'state': (0, 1), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 4, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (0, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (0, 1), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 0), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (1, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (1, 0), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'refresh_skip', 'state': (0, 1), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (0, 1), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (1, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (1, 1), 'g': 2, 'parent': (0, 1), 'h': 3, 'f': 5},
        {'type': 'refresh_skip', 'state': (1, 0), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (1, 0), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (2, 0), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 1, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (2, 0), 'g': 2, 'parent': (1, 0), 'h': 1, 'f': 3},
        {'type': 'refresh_skip', 'state': (2, 0), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (2, 0), 'g': 2, 'h': 1, 'f': 3},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 1), 'g': 3, 'parent': (2, 0), 'h': 2, 'f': 5},
        {'type': 'h_calc', 'state': (3, 0), 'value': 6, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 0, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 0), 'g': 3, 'parent': (2, 0), 'h': 0, 'f': 3},
        {'type': 'refresh_skip', 'state': (3, 0), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (3, 0), 'g': 3, 'h': 0, 'f': 3},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 1), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (3, 1), 'g': 4, 'parent': (3, 0), 'h': 2, 'f': 6},
        {'type': 'on_goal', 'state': (3, 0), 'g': 3, 'reason': 'expanded', 'goal_index': 1},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'update', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 3, 'phase': 'update'},
        {'type': 'pop_stale', 'state': (2, 1), 'f_stored': 5, 'f_recomputed': 6},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 2, 'h_new': 3},
        {'type': 'refresh_skip', 'state': (1, 1), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (1, 1), 'g': 2, 'h': 3, 'f': 5},
        {'type': 'refresh_skip', 'state': (3, 1), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (3, 1), 'g': 4, 'h': 2, 'f': 6},
        {'type': 'h_calc', 'state': (3, 2), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 2), 'value': 1, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 2), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (3, 2), 'g': 5, 'parent': (3, 1), 'h': 1, 'f': 6},
        {'type': 'refresh_skip', 'state': (3, 2), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (3, 2), 'g': 5, 'h': 1, 'f': 6},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 2), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 2), 'g': 6, 'parent': (3, 2), 'h': 2, 'f': 8},
        {'type': 'h_calc', 'state': (3, 3), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 3), 'value': 0, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 3), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 3), 'g': 6, 'parent': (3, 2), 'h': 0, 'f': 6},
        {'type': 'refresh_skip', 'state': (3, 3), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (3, 3), 'g': 6, 'h': 0, 'f': 6},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 3), 'g': 7, 'parent': (3, 3), 'h': 2, 'f': 9},
        {'type': 'on_goal', 'state': (3, 3), 'g': 6, 'reason': 'expanded', 'goal_index': 2},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'update', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'pop_stale', 'state': (2, 1), 'f_stored': 6, 'f_recomputed': 7},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 3, 'h_new': 4},
        {'type': 'refresh_skip', 'state': (2, 1), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (2, 1), 'g': 3, 'h': 4, 'f': 7},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 2), 'g': 4, 'parent': (2, 1), 'h': 3, 'f': 7},
        {'type': 'refresh_skip', 'state': (2, 2), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (2, 2), 'g': 4, 'h': 3, 'f': 7},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 3), 'g': 5, 'parent': (2, 2), 'h': 2, 'f': 7},
        {'type': 'refresh_skip', 'state': (2, 3), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (2, 3), 'g': 5, 'h': 2, 'f': 7},
        {'type': 'h_calc', 'state': (1, 3), 'value': 1, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (1, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (1, 3), 'g': 6, 'parent': (2, 3), 'h': 1, 'f': 7},
        {'type': 'refresh_skip', 'state': (1, 3), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (1, 3), 'g': 6, 'h': 1, 'f': 7},
        {'type': 'h_calc', 'state': (0, 3), 'value': 0, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (0, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (0, 3), 'g': 7, 'parent': (1, 3), 'h': 0, 'f': 7},
        {'type': 'refresh_skip', 'state': (0, 3), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (0, 3), 'g': 7, 'h': 0, 'f': 7},
        {'type': 'on_goal', 'state': (0, 3), 'g': 7, 'reason': 'expanded', 'goal_index': 0},
    ]
    assert actual == expected


# === lazy_opt_sv (119 events) ===
def test_recording_canonical_omspp_min_lazy_opt_sv() -> None:
    """
    ========================================================================
     Pin the FULL event stream for KAStarAgg-MIN with
     is_lazy=True, is_opt=True, store_vector=True.
     119 events.
    ========================================================================
    """
    p = ProblemGrid.Factory.grid_4x4_obstacle_omspp()
    algo = KAStarAgg(problem=p,
                     h=lambda s, g: float(s.distance(g)),
                     agg='MIN',
                     is_lazy=True,
                     is_opt=True,
                     store_vector=True,
                     is_recording=True)
    algo.run()
    actual = [normalize(e) for e in algo.recorder.events]
    expected = [
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 0), 'value': 6, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (0, 0), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 0), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (0, 0), 'g': 0, 'parent': None, 'h': 3, 'f': 3},
        {'type': 'refresh_skip', 'state': (0, 0), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (0, 0), 'g': 0, 'h': 3, 'f': 3},
        {'type': 'h_calc', 'state': (0, 1), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 4, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (0, 1), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (0, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (0, 1), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 0), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 0), 'value': 5, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (1, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (1, 0), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (1, 0), 'g': 1, 'parent': (0, 0), 'h': 2, 'f': 3},
        {'type': 'refresh_skip', 'state': (0, 1), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (0, 1), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 3, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (1, 1), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (1, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 1), 'value': 3, 'phase': 'search'},
        {'type': 'push', 'state': (1, 1), 'g': 2, 'parent': (0, 1), 'h': 3, 'f': 5},
        {'type': 'refresh_skip', 'state': (1, 0), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (1, 0), 'g': 1, 'h': 2, 'f': 3},
        {'type': 'h_calc', 'state': (2, 0), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 1, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 0), 'value': 4, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (2, 0), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (2, 0), 'g': 2, 'parent': (1, 0), 'h': 1, 'f': 3},
        {'type': 'refresh_skip', 'state': (2, 0), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (2, 0), 'g': 2, 'h': 1, 'f': 3},
        {'type': 'h_calc', 'state': (2, 1), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 2, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (2, 1), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 1), 'g': 3, 'parent': (2, 0), 'h': 2, 'f': 5},
        {'type': 'h_calc', 'state': (3, 0), 'value': 6, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 0, 'phase': 'search', 'goal': (3, 0)},
        {'type': 'h_calc', 'state': (3, 0), 'value': 3, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 0), 'responsible': (3, 0)},
        {'type': 'phi_calc', 'state': (3, 0), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 0), 'g': 3, 'parent': (2, 0), 'h': 0, 'f': 3},
        {'type': 'refresh_skip', 'state': (3, 0), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (3, 0), 'g': 3, 'h': 0, 'f': 3},
        {'type': 'h_calc', 'state': (3, 1), 'value': 5, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 1), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 1), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 1), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (3, 1), 'g': 4, 'parent': (3, 0), 'h': 2, 'f': 6},
        {'type': 'on_goal', 'state': (3, 0), 'g': 3, 'reason': 'expanded', 'goal_index': 1},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 3, 'phase': 'update'},
        {'type': 'pop_stale', 'state': (2, 1), 'f_stored': 5, 'f_recomputed': 6},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 2, 'h_new': 3},
        {'type': 'refresh_skip', 'state': (1, 1), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (1, 1), 'g': 2, 'h': 3, 'f': 5},
        {'type': 'refresh_skip', 'state': (3, 1), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (3, 1), 'g': 4, 'h': 2, 'f': 6},
        {'type': 'h_calc', 'state': (3, 2), 'value': 4, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 2), 'value': 1, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 2), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 2), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (3, 2), 'g': 5, 'parent': (3, 1), 'h': 1, 'f': 6},
        {'type': 'refresh_skip', 'state': (3, 2), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (3, 2), 'g': 5, 'h': 1, 'f': 6},
        {'type': 'h_calc', 'state': (2, 2), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (2, 2), 'value': 2, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 2), 'g': 6, 'parent': (3, 2), 'h': 2, 'f': 8},
        {'type': 'h_calc', 'state': (3, 3), 'value': 3, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'h_calc', 'state': (3, 3), 'value': 0, 'phase': 'search', 'goal': (3, 3)},
        {'type': 'responsible_set', 'state': (3, 3), 'responsible': (3, 3)},
        {'type': 'phi_calc', 'state': (3, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (3, 3), 'g': 6, 'parent': (3, 2), 'h': 0, 'f': 6},
        {'type': 'refresh_skip', 'state': (3, 3), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (3, 3), 'g': 6, 'h': 0, 'f': 6},
        {'type': 'h_calc', 'state': (2, 3), 'value': 2, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (2, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'push', 'state': (2, 3), 'g': 7, 'parent': (3, 3), 'h': 2, 'f': 9},
        {'type': 'on_goal', 'state': (3, 3), 'g': 6, 'reason': 'expanded', 'goal_index': 2},
        {'type': 'responsible_set', 'state': (2, 1), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 1), 'value': 4, 'phase': 'update'},
        {'type': 'pop_stale', 'state': (2, 1), 'f_stored': 6, 'f_recomputed': 7},
        {'type': 'update_heuristic', 'state': (2, 1), 'h_old': 3, 'h_new': 4},
        {'type': 'refresh_skip', 'state': (2, 1), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (2, 1), 'g': 3, 'h': 4, 'f': 7},
        {'type': 'responsible_set', 'state': (2, 2), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 2), 'value': 3, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 2), 'g': 4, 'parent': (2, 1), 'h': 3, 'f': 7},
        {'type': 'refresh_skip', 'state': (2, 2), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (2, 2), 'g': 4, 'h': 3, 'f': 7},
        {'type': 'responsible_set', 'state': (2, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (2, 3), 'value': 2, 'phase': 'search'},
        {'type': 'decrease_g', 'state': (2, 3), 'g': 5, 'parent': (2, 2), 'h': 2, 'f': 7},
        {'type': 'refresh_skip', 'state': (2, 3), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (2, 3), 'g': 5, 'h': 2, 'f': 7},
        {'type': 'h_calc', 'state': (1, 3), 'value': 1, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (1, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (1, 3), 'value': 1, 'phase': 'search'},
        {'type': 'push', 'state': (1, 3), 'g': 6, 'parent': (2, 3), 'h': 1, 'f': 7},
        {'type': 'refresh_skip', 'state': (1, 3), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (1, 3), 'g': 6, 'h': 1, 'f': 7},
        {'type': 'h_calc', 'state': (0, 3), 'value': 0, 'phase': 'search', 'goal': (0, 3)},
        {'type': 'responsible_set', 'state': (0, 3), 'responsible': (0, 3)},
        {'type': 'phi_calc', 'state': (0, 3), 'value': 0, 'phase': 'search'},
        {'type': 'push', 'state': (0, 3), 'g': 7, 'parent': (1, 3), 'h': 0, 'f': 7},
        {'type': 'refresh_skip', 'state': (0, 3), 'reason': 'lazy_responsible_active'},
        {'type': 'pop', 'state': (0, 3), 'g': 7, 'h': 0, 'f': 7},
        {'type': 'on_goal', 'state': (0, 3), 'g': 7, 'reason': 'expanded', 'goal_index': 0},
    ]
    assert actual == expected
